# General config
set -g mouse on
set -g history-limit 10000
set -sg escape-time 0

# Pane start from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Tab rename
set -g automatic-rename off
set -g allow-rename off

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Tab style
set -g status on
set -g status-justify left
set -g status-interval 2
set -g status-style bg=default,fg=white

set -g status-left-length 30
set -g status-left "#[fg=#bd93f9,bold][#S] #[default]"


set -g window-status-current-format "#[bg=#bd93f9,fg=#000000,bold]#I: #W#F "
set -g window-status-format "#[fg=#bd93f9]#I: #W "

set -g status-right-length 100
set -g status-right "#[fg=#bb9af7]CPU: #[fg=white]#(top -bn1 | grep 'Cpu(s)' | awk '{print $2}')% #[fg=#444444]| #[fg=#bb9af7]MEM: #[fg=white]#(free -m | awk '/Mem:/ { printf \"%%.0f%%\", $3/$2*100 }') #[fg=#444444]| #[fg=#bb9af7,bold]%H:%M "


# Change prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Easy tab splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# Pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Pane zoom
bind z resize-pane -Z

# Set mode keys as vi
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "clip.exe"

# Disable some notification
setw -g monitor-activity on
set -g visual-activity on

set -g focus-event on

# Reload configuration
bind r source-file ~/.tmux.conf \; display-message "Reloaded"
