# General config
set -g mouse on
set -g history-limit 10000
set -sg escape-time 0

# Pane start from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Tab rename
set -g automatic-rename off
set -g allow-rename off

# Tab style
set -g status on
set -g status-justify left
set -g status-style bg=black,fg=white
set -g window-status-style fg=white,bg=black
set -g window-status-current-style fg=white,bg=#606060
set -g window-status-format "#[fg-cyan]#I #[fg=white]#W"
set -g window-status-current-format "#[bold] #I #W "

# Change prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Easy tab splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# Pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Pane zoom
bind z resize-pane -Z

# Set mode keys as vi
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "clip.exe"

# Disable some notification
setw -g monitor-activity on
set -g visual-activity on

set -g focus-event on

# Reload configuration
bind r source-file ~/.tmux.conf \; display-message "Reloaded"
